name: algolia
version: 1.0.0+1
description: >
   Algolia is a pure dart SDK, wrapped around Algolia REST API for easy implementation for your Flutter or Dart projects.
homepage: https://github.com/knoxpo/dart_algolia

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  uuid: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
