name: algolia
description: >
   Algolia is a pure dart SDK, wrapped around Algolia REST API for easy implementation for your Flutter or Dart projects.
version: 1.1.0+1
repository: https://github.com/knoxpo/dart_algolia
homepage: https://knoxpo.com/knoxpo/dart_algolia

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.6.0
  http: ^0.13.0
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  dotenv: ^3.0.0
